title: inventorySettings
type: object
description: Reader settings for inventory mode.
properties:
  interval:
    type: object
    description: The time interval (how often) to perform inventory
    properties:
      unit:
        type: string
        enum:
          - seconds
          - minutes
          - hours
          - days
      value:
        type: integer
