openapi: 3.0.0
info:
  title: FX Reader Management
  version: '2.0'
  description: Management and integration of Zebra RFID readers in the cloud
  contact:
    email: support@zebra.com
tags:
  - name: Management
    description: Reader Management
  - name: Control
    description: Radio Control
paths:
  /cloud/version:
    parameters: []
    get:
      summary: Retrieves reader component version information
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../models/reader/info/readerversion.v1.yaml
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: ../models/error.v1.yaml
        '500':
          description: Internal Device Error
          content:
            application/json:
              schema:
                $ref: ../models/error.v1.yaml
      operationId: get_version
      description: 'Retrieves reader component version information including Boot Loader, OS, Reader Application, and Radio Firmware versions'
      tags:
        - Management
  /cloud/network:
    parameters: []
    get:
      summary: Retrieves reader network configuration
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../models/reader/info/readernetwork.v1.yaml
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: ../models/error.v1.yaml
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: ../models/error.v1.yaml
      operationId: get_network
      description: 'Retrieves reader network information including IP address, subnet mask, gateway and DNS'
      tags:
        - Management
    put:
      summary: Updates reader network configuration
      operationId: set_network
      responses:
        '200':
          description: OK
          content:
            text/html:
              schema:
                description: Command Successful
                type: string
                default: Command Successful
                example: Command Successful
      description: Updates the reader network configuration settings
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../models/reader/config/networkconfig.v1.yaml
        description: ''
      tags:
        - Management
  /cloud/status:
    parameters: []
    get:
      summary: Retrieves reader operational statistics
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../models/reader/info/readerstats.v1.yaml
        '202':
          description: Accepted
          content:
            application/json:
              schema:
                $ref: ../models/reader/info/readerupgradestatus.v1.yaml
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: ../models/error.v1.yaml
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: ../models/error.v1.yaml
      operationId: get_status
      description: Retrieves reader operational statistics for read points
      tags:
        - Management
  /cloud/reboot:
    parameters: []
    put:
      summary: Restarts reader
      responses:
        '202':
          description: Accepted
          headers:
            Location:
              description: A URL that will provide a status of the restart
              schema:
                type: string
                example: 'https://mock-api.zebra.com/v2/rfid-read-to-cloud/status'
          content:
            text/html:
              schema:
                type: string
                default: Reboot Pending
                description: Restart Pending
                example: Reboot Pending
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: ../models/error.v1.yaml
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: ../models/error.v1.yaml
      operationId: reboot
      description: Restarts the reader with the device ID provided
      tags:
        - Management
  /cloud/gpo:
    put:
      summary: Updates GPO port state
      operationId: set_gpo
      description: Updates the GPO state on the specified port of the reader
      parameters:
        - in: query
          name: port
          description: The GPO port ID
          required: true
          schema:
            type: integer
        - in: query
          name: state
          description: The GPO state signal to send
          required: true
          schema:
            type: boolean
      responses:
        '200':
          description: OK
          content:
            text/html:
              schema:
                description: Command Successful
                type: string
                default: Command Successful
                example: Command Successful
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: ../models/error.v1.yaml
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: ../models/error.v1.yaml
      tags:
        - Management
    parameters: []
  /cloud/app-led:
    put:
      summary: Updates application LED state
      operationId: set_appled
      description: Updates the application LED state on the reader to the state specified
      parameters:
        - in: query
          name: color
          description: 'The color of the LED (red, amber, green)'
          required: true
          schema:
            type: string
            enum:
              - red
              - amber
              - green
        - in: query
          name: seconds
          description: The duration in seconds for the LED state to be in effect
          required: true
          schema:
            type: integer
        - in: query
          name: flash
          description: A value indicating whether to flash the LED
          required: false
          schema:
            type: boolean
      responses:
        '200':
          description: OK
          content:
            text/html:
              schema:
                description: Command Successful
                type: string
                default: Command Successful
                example: Command Successful
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: ../models/error.v1.yaml
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: ../models/error.v1.yaml
      tags:
        - Management
    parameters: []
    get:
      summary: Retrieves application LED state
      operationId: get_appled
      responses:
        '200':
          description: OK
          content:
            text/html:
              schema:
                type: string
                enum:
                  - DEFAULT
                  - NON_DEFAULT
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: ../models/error.v1.yaml
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: ../models/error.v1.yaml
      description: Retrieves a value indicating the current state of the application LED
      tags:
        - Management
  /cloud/region:
    parameters: []
    get:
      summary: Retrieves reader region information
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../models/reader/config/regionconfig.v1.yaml
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: ../models/error.v1.yaml
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: ../models/error.v1.yaml
      operationId: get_region
      description: Retrieves reader region (country) information
      tags:
        - Management
  /cloud/start:
    parameters: []
    put:
      summary: Starts reading tags
      responses:
        '200':
          description: OK
          content:
            text/html:
              schema:
                description: Command Successful
                type: string
                default: Command Successful
                example: Command Successful
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: ../models/error.v1.yaml
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: ../models/error.v1.yaml
      operationId: start
      description: Starts the reader reading tags
      tags:
        - Control
  /cloud/stop:
    parameters: []
    put:
      summary: Stops reading tags
      responses:
        '200':
          description: OK
          content:
            text/html:
              schema:
                description: Command Successful
                type: string
                default: Command Successful
                example: Command Successful
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: ../models/error.v1.yaml
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: ../models/error.v1.yaml
      operationId: stop
      description: Stops the reader reading tags
      tags:
        - Control
  /cloud/mode:
    get:
      summary: Retrieves operating mode
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../models/reader/config/modes/operatingMode.v1.yaml
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: ../models/error.v1.yaml
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: ../models/error.v1.yaml
      operationId: get_mode
      description: Retrieves current operating mode
      tags:
        - Control
    put:
      summary: Updates identification mode
      responses:
        '200':
          description: OK
          content:
            text/html:
              schema:
                description: Command Successful
                type: string
                default: Command Successful
                example: Command Successful
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: ../models/error.v1.yaml
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: ../models/error.v1.yaml
      operationId: set_mode
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../models/reader/config/modes/operatingMode.v1.yaml
        description: The new identification mode
      description: "Changes the reader's operating mode"
      tags:
        - Control
    parameters: []
  /cloud/os:
    parameters: []
    put:
      summary: Updates software on device
      responses:
        '202':
          description: Accepted
          headers:
            Location:
              schema:
                type: string
                example: 'https://mock-api.zebra.com/v2/rfid-read-to-cloud/status'
              description: A URL that provides a status on the update
              required: true
      operationId: set_os
      requestBody:
        content:
          application/gzip:
            schema:
              type: string
              format: uri
              example: 'https://www.zebra.com/apps/dlmanager?dlp=-227178c9720c025483893483886ea540bd07dd0f9873752cf891686eb495040ba85f97bf163f9fd12080ee1978f57c98463270ae549b1b5c65e6acbef65100a1978a205f64aae7c7ef1d957c10a43f885d113b42e079e0119302a877e3ec811c409967895fc977bd97b1c080e9d4771&c=us&l=en'
        description: A link to the OS software update package .zip file
      description: Update the OS software on the device
      tags:
        - Management
  '{readerAddress}/cloud/config':
    parameters:
      - schema:
          type: string
        name: readerAddress
        in: path
        required: true
    put:
      summary: Updates reader configuration
      responses:
        '200':
          description: OK
          content:
            text/html:
              schema:
                description: Command Successful
                type: string
                default: Command Successful
                example: Command Successful
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: ../models/error.v1.yaml
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: ../models/error.v1.yaml
      operationId: set_config
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                xml:
                  type: string
                  description: The current reader configuration XML string
        description: The new reader configuration XML file
      description: Updates the reader configuration
      tags:
        - Management
    get:
      summary: Retrieves reader configuration
      operationId: get_config
      description: Retrieves reader configuration
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  xml:
                    type: string
                    description: The current reader configuration XML string
      tags:
        - Management
  /cloud/logs:
    get:
      summary: Log Configuration
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../models/reader/config/logLevel.v1.json
          headers: {}
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: ../models/error.v1.yaml
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: ../models/error.v1.yaml
      operationId: get_logs
      description: Retrieves reader log configuration
      tags:
        - Management
    put:
      summary: Configures the logs
      responses:
        '200':
          description: OK
          content:
            text/html:
              schema:
                description: Command Successful
                type: string
                default: Command Successful
                example: Command Successful
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: ../models/error.v1.yaml
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: ../models/error.v1.yaml
      operationId: set_logs
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../models/reader/config/logLevel.v1.json
        description: The log level to configure
      description: Changes logging level
      tags:
        - Management
    parameters: []
  '/cloud/logs/{logType}':
    parameters:
      - schema:
          type: string
          enum:
            - syslog
            - radioPacketLog
        name: logType
        in: path
        required: true
        description: Type of Log to Retrieve
    get:
      summary: Retrieve Log
      responses:
        '200':
          description: OK
          content:
            application/gzip:
              schema:
                description: Reader Logs Retrieved
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: ../models/error.v1.yaml
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: ../models/error.v1.yaml
      operationId: get_logs_syslog
      tags:
        - Management
      description: Retrieves a reader log
    delete:
      summary: Purge Log
      operationId: del_logs_syslog
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: ../models/error.v1.yaml
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: ../models/error.v1.yaml
      description: Purges a particular log
      tags:
        - Management
servers:
  - url: '{protocol}://{readerAddress}'
    variables:
      readerAddress:
        default: 169.254.10.1
        description: Reader Address
      protocol:
        enum:
          - http
          - https
        default: https
  - description: ''
components:
  securitySchemes: {}
